In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# B-Spline basic function definition
# It requires input i=,k=Degree of the function and u values which are knot values divided for generating curve
def N(i,k,u):
    #This has to be generated from knot vector function. Here its written manually
    #t=np.array([0., 0., 0., 1., 2., 3., 4., 4.,4.])
    if k==0:
        if t[i] <= u < t[i+1]:
            return 1
        else:
            return 0
    else:
        # If else loop is used to avoid division by zero.
        if (t[i+k]-t[i]) == 0:
            first_term=0
        else:
            first_term = ((u-t[i])*(N(i,k-1,u))/(t[i+k]-t[i]))
        if (t[i+k+1]-t[i+1]) == 0:
            second_term = 0
        else:
            second_term = ((t[i+k+1]-u)*(N(i+1,k-1,u))/(t[i+k+1]-t[i+1]))
        #return(((u-t[i])*(N(i,k-1,u))/(t[i+k-1]-t[i])) + ((t[i+k]-u)*(N(i+1,k-1,u))/(t[i+k]-t[i+1])))
        return(first_term+second_term)

In [3]:
#Parameters
#Have to modify to in each segment
control_points_x=3
control_points_x=4
n_x=control_points_x-1
n_y=control_points_y-1
degree_x=2
degree_y=2
number_of_segments_x=n_x-(degree_x+1)+2
number_of_segments_x=n_y-(degree_y+1)+2
#u=np.arange(0,number_of_segments+1,1)

In [6]:
P_xy = np.array([[[0., 0.],[1., 0.],[2., 0.]],[[0., 1.],[1., 1.],[2., 1.]],[[0., 2.],[1., 2.],[2., 2.]]])
print(P_xy)


[[[0. 0.]
  [1. 0.]
  [2. 0.]]

 [[0. 1.]
  [1. 1.]
  [2. 1.]]

 [[0. 2.]
  [1. 2.]
  [2. 2.]]]
