In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
def N(i,k,u):
    t=np.array([0., 0., 0., 1., 2., 3., 4., 4., 4.])
    if k==0:
        if t[i] <= u < t[i+1]:
            return 1
        else:
            return 0
    else:
        if (t[i+k-1]-t[i]) == 0:
            first_term=0
        else:
            first_term = ((u-t[i])*(N(i,k-1,u))/(t[i+k-1]-t[i]))
        if (t[i+k]-t[i+1]) == 0:
            second_term = 0
        else:
            second_term = ((t[i+k]-u)*(N(i+1,k-1,u))/(t[i+k]-t[i+1]))
        #return(((u-t[i])*(N(i,k-1,u))/(t[i+k-1]-t[i])) + ((t[i+k]-u)*(N(i+1,k-1,u))/(t[i+k]-t[i+1])))
        return(first_term+second_term)

In [3]:
t=np.array([0., 0., 0., 1., 2., 3., 4., 4., 4.])
t

array([0., 0., 0., 1., 2., 3., 4., 4., 4.])

In [4]:
#Parameters
control_points=5
n=control_points-1
degree=3
number_of_segments=n-degree+2
u=np.arange(0,number_of_segments+1,1)

In [11]:
B_Func=np.zeros((control_points,10))
for i in range(control_points):
    u1=np.linspace(i,i+1,10)
    for j,u in enumerate(u1):
        B_Func[i,j] = N(i,degree,u)        
        
print(B_Func)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 