In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math
from scipy import special
np.set_printoptions(threshold=np.inf)

## Small example for binomial coefficient nCr using scipy

In [2]:
B=special.binom(0, 0) #binom(n,r)
print(B)

1.0


## Find Span

In [3]:
def FindSpan(n_inp,degree_inp,u_inp,knot_vector_inp):
    x=knot_vector_inp[degree_inp+1]
    if (u_inp < x):
        return degree_inp
    else:
        for i,pos in enumerate(knot_vector_inp):
            if math.floor(u_inp) == pos:
                return (i)

## Non Zero Basis Functions

In [4]:
#The output is stored in N[0],....N[p]
#These are non zero functions in a given span
#i is the span of the u value
#we get N[i-p].........,N[i]
# So if i is 3 then N[3] is stored in N[p] of the output matrix
def BasisFuns(i,u,p,U):
    N =np.zeros(p+1)
    N[0] = 1.0
    left =np.zeros(p+2)
    right =np.zeros(p+2)
    for j in range(1,p+1):
        left[j] = u - U[i+1-j]
        right[j] = U[i+j] - u
        saved= 0.0
        for r in range(0,j):
            temp = N[r]/(right[r+1]+left[j-r])
            N[r] = saved + right[r+1]*temp
            saved = left[j-r]*temp
        N[j] = saved
    return N

## Derivatives of Non_Zero basis Functions

In [5]:
# Derivatives are stored in ders[k][j]
# ders[k][j] is the kth derivative of function N_(i-p+j,p)
# If k>p the derivatives are zero.
def DersBasisFuns(i,u,p,m,U):
    #Inititation of dimentions for 2D matrices
    ndu=np.zeros((p+1,p+1))
    ders=np.zeros((p+1,p+1))
    a=np.zeros((2,p+1))
    left =np.zeros(p+2)
    right =np.zeros(p+2)
    
    ndu[0][0]=1.0
    for j in range(1,p+1):
        left[j] = u - U[i+1-j]
        right[j] = U[i+j] - u
        saved=0.0
        for r in range(j):
            #Lower triangle
            ndu[j][r] = right[r+1]+left[j-r]
            temp=ndu[r][j-1]/ndu[j][r]
            #Upper triangle
            ndu[r][j] = saved+(right[r+1]*temp)
            saved=left[j-r]*temp
        ndu[j][j] = saved
    for j in range (p+1): #Load the basis functions
        ders[0][j]=ndu[j][p]
    #This secion computes the derivatives
    for r in range(p+1):
        s1=0
        s2=1 #Alternative rows in array a
        a[0][0] = 1.0
        #Loop to compute kth derivative
        for k in range(1,m+1):
            d=0.0
            rk=r-k
            pk=p-k
            if(r>=k):
                a[s2][0]=a[s1][0]/ndu[pk+1][rk]
                d=a[s2][0]*ndu[rk][pk]
            if(rk>=-1):
                j1=1
            else:
                j1=-rk
            if(r-1<=pk):
                j2=k-1
            else:
                j2=p-r
            for j in range (j1,j2+1):
                a[s2][j] =(a[s1][j]-a[s1][j-1])/ndu[pk+1][rk+j]
                d += (a[s2][j]*ndu[rk+j][pk])
            if(r<=pk):
                a[s2][k]=-a[s1][k-1]/ndu[pk+1][r]
                d+=(a[s2][k]*ndu[r][pk])
            ders[k][r]=d
            #Switch rows
            j=s1
            s1=s2
            s2=j
            #Multiply through by the correct factors
    r=p
    for k in range(1,m+1):
        for j in range(p+1):
            ders[k][j] =ders[k][j]* r
        r =r* (p-k)
    return ders

## Aders

In [6]:
#An extra W is given as input to function for convinience which contain weights of corresponding control points
def SurfaceDerivsAlgAuv(n,p,U,m,q,V,P,W,u,v,d):
    #SKL=np.zeros((p+1,q+1,3))
    SKL=np.zeros((20,20,3))
    temp=np.zeros((q+1,3))
    #print(SKL)
    #print(temp[0])
    #print(P[1][1])
    du = min(d,p)
    for k in range(p+1,d+1):
        for l in range(d-k+1):
            SKL[k][l]=0.0
    dv = min(d,q)
    for l in range(q+1,d+1):
        for k in range(d-l+1):
            SKL[k][l]=0.0 
    uspan=FindSpan(n,p,u,U)
    unders=DersBasisFuns(uspan,u,p,du,U)
    vspan=FindSpan(m,q,v,V)
    vnders=DersBasisFuns(vspan,v,q,dv,V)
    for k in range(du+1):
        for s in range(q+1):
            temp[s] = 0.0
            for r in range(p+1):
                temp[s]=temp[s] + unders[k][r]*P[uspan-p+r][vspan-q+s]*W[uspan-p+r][vspan-q+s]
            dd=min(d-k,dv)
            for l in range(dd+1):
                SKL[k][l] = 0.0
                for s in range(q+1):
                    SKL[k][l] = SKL[k][l] + vnders[l][s]*temp[s]
    return SKL #Returning Aders here

## wders

In [7]:
def SurfaceDerivsAlgWuv(n,p,U,m,q,V,P,W,u,v,d):
    #SKL=np.zeros((p+1,q+1,1)) #Have to cross check if this is right way of dimensioning SKL
    SKL=np.zeros((20,20,1))
    temp=np.zeros((q+1,1))    # Have to be because W is a scalar unlike P which is vector
    #print(SKL)
    #print(temp[0])
    #print(P[1][1])
    du = min(d,p)
    for k in range(p+1,d+1):
        for l in range(d-k+1):
            SKL[k][l]=0.0
    dv = min(d,q)
    for l in range(q+1,d+1):
        for k in range(d-l+1):
            SKL[k][l]=0.0 
    uspan=FindSpan(n,p,u,U)
    #print('USPAN',uspan)
    unders=DersBasisFuns(uspan,u,p,du,U)
    vspan=FindSpan(m,q,v,V)
    #print('VSPAN',vspan)
    vnders=DersBasisFuns(vspan,v,q,dv,V)
    for k in range(du+1):
        for s in range(q+1):
            temp[s] = 0.0
            for r in range(p+1):
                temp[s]=temp[s] + unders[k][r]*W[uspan-p+r][vspan-q+s]
            dd=min(d-k,dv)
            for l in range(dd+1):
                SKL[k][l] = 0.0
                for s in range(q+1):
                    SKL[k][l] = SKL[k][l] + vnders[l][s]*temp[s]
    return SKL #Returning wders here

## Only derivatives of NURBS Functions

In [8]:
def SurfaceDerivsAlgNURBS(n,p,U,m,q,V,P,W,u,v,d):
    #SKL=np.zeros((p+1,q+1,1)) #Have to cross check if this is right way of dimensioning SKL
    SKL=np.zeros((20,20,1))
    temp=np.zeros((q+1,1))    # Have to be because W is a scalar unlike P which is vector
    #print(SKL)
    #print(temp[0])
    #print(P[1][1])
    du = min(d,p)
    for k in range(p+1,d+1):
        for l in range(d-k+1):
            SKL[k][l]=0.0
    dv = min(d,q)
    for l in range(q+1,d+1):
        for k in range(d-l+1):
            SKL[k][l]=0.0 
    uspan=FindSpan(n,p,u,U)
    #print('USPAN',uspan)
    unders=DersBasisFuns(uspan,u,p,du,U)
    vspan=FindSpan(m,q,v,V)
    #print('VSPAN',vspan)
    vnders=DersBasisFuns(vspan,v,q,dv,V)
    for k in range(du+1):
        for s in range(q+1):
            temp[s] = 0.0
            for r in range(p+1):
                temp[s]=temp[s] + unders[k][r]
            dd=min(d-k,dv)
            for l in range(dd+1):
                SKL[k][l] = 0.0
                for s in range(q+1):
                    SKL[k][l] = SKL[k][l] + vnders[l][s]*temp[s]
    return SKL #Returning wders with weights equal to 1 here

## Function to extract derivatives of NURBS Surface

In [9]:
#Functions gives SKL matrix which contain kth ans lth derivatives of the NURBS Surface function S(u,v)
#For example 1st derivative of S(u,v) wrt to xi_para is stored in SKL[1][0]
#Likewise 1st derivative of S(u,v) wrt to eta_para is stored in SKL[0][1]

def RatSurfaceDerivs(Aders,wders,d):
    #SKL=np.zeros((p+1,q+1,3))
    SKL=np.zeros((20,20,3))
    for k in range(d+1):
        for l in range(d-k+1):
            v=Aders[k][l]
            for j in range(1,l+1):
               # print('B',special.binom(l,j))
                v=v-special.binom(l,j)*wders[0][j]*SKL[k][l-j]
            for i in range(1,k+1):
                v=v-special.binom(k,i)*wders[i][0]*SKL[k-i][l]
                v2 = 0.0
                for j in range(1,l+1):
                    v2=v2+special.binom(l,j)*wders[i][j]*SKL[k-i][l-j]
                v = v-special.binom(k,i)*v2
            SKL[k][l] = v/wders[0][0]
    return SKL

## Higher (4th) Order  element p=3, q=3

In [10]:
#----------Manually change below variables--------------#
p=3
q=3
U=np.array([0., 0., 0., 0., 1., 2., 2., 2., 2.])
V=np.array([0., 0., 0., 0., 1., 2., 2., 2., 2.])
P_W=np.array([[[0,0,0,1],[0,0.25,0,1],[0,0.5,0,1],[0,0.75,0,1],[0,1,0,1]],
              [[0.25,0,0,1],[0.25,0.25,0,1],[0.25,0.5,0,1],[0.25,0.75,0,1],[0.25,1,0,1]],
              [[0.5,0,0,1],[0.5,0.25,0,1],[0.5,0.5,0,1],[0.5,0.75,0,1],[0.5,1,0,1]],
              [[0.75,0,0,1],[0.75,0.25,0,1],[0.75,0.5,0,1],[0.75,0.75,0,1],[0.75,1,0,1]],
              [[1.0,0,0,1],[1.0,0.25,0,1],[1.0,0.5,0,1],[1.0,0.75,0,1],[1.0,1,0,1]]])
d=2
ndof = 2
#----------For Verification with 2nd order equations------------#
# p=1
# q=1
# U = np.array([0., 0., 1.,1.]) 
# V = np.array([0., 0., 1.,1.]) 
# P_W=np.array([[[0,0,0,1],[0,1,0,1]],
#            [[1,0,0,1],[1,1,0,1]]])
# d=1
# ndof = 2
#---------------------------------------------------------------#



#-----------GAUSS POINTS---------------#
GPs_Ws = np.array([[-0.8611,-0.8611,0.1210],[-0.8611,-0.3399,0.2269],[-0.8611,0.3399,0.2269],[-0.8611,0.8611,0.1210],
                   [-0.3399,-0.8611,0.2269],[-0.3399,-0.3399,0.4253],[-0.3399,0.3399,0.4253],[-0.3399,0.8611,0.2269],
                   [0.3399,-0.8611,0.2269],[0.3399,-0.3399,0.4253],[0.3399,0.3399,0.4253],[0.3399,0.8611,0.2269],
                   [0.8611,-0.8611,0.1210],[0.8611,-0.3399,0.2269],[0.8611,0.3399,0.2269],[0.8611,0.8611,0.1210]])
#----------Need not alter below variables--------------#
n=(np.size(U)-1)-p-1
m=(np.size(V)-1)-q-1
P=P_W[:,:,0:3]
W=P_W[:,:,3]
ncpxi=np.shape(P_W)[1]  #No.of control points xi direction
ncpeta=np.shape(P_W)[1] #No.of control points eta direction
nel=(ncpxi-p-1)*(ncpeta-q-1)
ncp = ncpxi*ncpeta #Total number of control points
necp = (p+2)*(q+2) #Total number of control points per element

## Loop over gauss points

In [23]:
KG = np.zeros((ndof*ncp,ndof*ncp)) #Initiating Global K matrix
RHSG = np.zeros((ndof*ncp,1)) # Initiating Global RHS matrix
for i in range(nel):
    Ke=np.zeros((ndof*necp,ndof*necp))
    B=np.zeros((3,ndof*necp)) #Dimentions depends on type of application
    elU = np.array([0,2]) #Manually defined have to generate using connectivity functions
    elV = np.array([0,2]) #Manually defined have to generate using connectivity functions
    
    #-------------------GAUSS LOOP-------------------#
    for j in range(np.shape(GPs_Ws)[0]):
    #for j in range(2):
        gp = GPs_Ws[j,0:2]
        wg = GPs_Ws[j,2]
        ximas = gp[0]
        etamas = gp[1]
        xi = 0.5*((elU[1]-elU[0])*ximas + (elU[1]+elU[0]))     #Paramteric co-ordinates
        eta = 0.5*((elV[1]-elV[0])*etamas + (elV[1]+elV[0]))
        dxi_dximas = 0.5*(elU[1]-elU[0])
        deta_detamas = 0.5*(elV[1]-elV[0]) 
        J2 = dxi_dximas*deta_detamas
        #--------Evaluation of NURBS basis functions derivatives---------#
        Aders = SurfaceDerivsAlgAuv(n,p,U,m,q,V,P,W,xi,eta,d)
        wders = SurfaceDerivsAlgWuv(n,p,U,m,q,V,P,W,xi,eta,d)
        dRx = RatSurfaceDerivs(Aders,wders,d)
        dRx_dxi  =  dRx[1][0][0]
        dRx_deta =  dRx[0][1][0]
        dRy_dxi  =  dRx[1][0][1]
        dRy_deta =  dRx[0][1][1]
        J1 = np.array([[dRx_dxi,dRx_deta],
                  [dRy_dxi,dRy_deta]])
        #print('J1 Matrix : ',J1)
        J1det = (dRx_dxi*dRy_deta)-(dRx_deta*dRy_dxi)
        #print('Determinat of J1 : ',J1det)
        J1inv = np.linalg.inv(J1)
        #print('J1inv : ',J1inv)
        #---------------NURBS Basis Functions Derivatives wrt x and y-------------#
        uspan = FindSpan(n,p,xi,U)
        vspan = FindSpan(m,q,eta,V)
        # Indices of non vanishing basis functions
        NVu = np.arange(uspan-p,uspan+1,1) #Thoroughly checked. Can crosscheck again
        NVv = np.arange(vspan-p,vspan+1,1)
        Den = SurfaceDerivsAlgWuv(n,p,U,m,q,V,P,W,xi,eta,d)
        Denom = Den[0][0]
        Denom_du = Den[1][0]
        Denom_dv = Den[0][1]
        dR_du = np.zeros((ncpxi,ncpxi))
        dR_dv = np.zeros((ncpxi,ncpxi))
        #---------------Loop over Non vanishing NURBS Basis Functions-------------#
        #***************Forgot to multiply with control points weights*************# Have to do it
        for ii, ii_value in enumerate(NVu):
            for jj, jj_value in enumerate(NVv):
                BFu = BasisFuns(uspan,xi,p,U)
                BFv = BasisFuns(vspan,eta,q,V)
                Num = BFu[ii]*BFv[jj]
                DBFu = DersBasisFuns(uspan,xi,p,d,U)
                DBFv = DersBasisFuns(vspan,eta,q,d,V)
                Num_du = DBFu[1][ii]*BFv[jj]
                Num_dv = BFu[ii]*DBFv[1][jj]
                dR_du[ii_value][jj_value] = Num_du/Denom - Denom_du*Num/(Denom*Denom)
                dR_dv[ii_value][jj_value] = Num_dv/Denom - Denom_dv*Num/(Denom*Denom)
        #---------Flatten (Convert 2D to 1D array) DervsNURBS Function------------#
        #dR_du(0,0)....dR_du(0,1),dR_du(1,0),.....dR_du(1,4).....dR_du(4,0),..........dR_du(4,4)
        fdR_du = dR_du.flatten()
        fdR_dv = dR_dv.flatten()
        #-------------------------B Matrix --------------------------#
        for i2 in range(necp):
            j1= 2*i
            j2= 2*i+1
            B[0,j1] = fdR_du[i2]
            B[1,j2] = fdR_dv[i2]
            B[2,j1] = fdR_dv[i2]
            B[2,j2] = fdR_du[i2]
        #------------------------- C Matrix--------------------------#
        C=np.array([[139000,74280,0],[74280,115400,0],[0,0,115400]])
        #-------------------------Local Stiffness matrix Ke-------------------#
        CB=np.matmul(C,B)
        BCB = np.matmul(np.transpose(B),CB)
        Ke = Ke + BCB*J1det*J2*wg
        print(Ke)
        
        

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

D:\Install_Path\Jupyter\Install\lib\site-packages\ipykernel_launcher.py:20: RuntimeWarning: divide by zero encountered in double_scalars
D:\Install_Path\Jupyter\Install\lib\site-packages\ipykernel_launcher.py:52: RuntimeWarning: divide by zero encountered in double_scalars
D:\Install_Path\Jupyter\Install\lib\site-packages\ipykernel_launcher.py:38: RuntimeWarning: divide by zero encountered in double_scalars
D:\Install_Path\Jupyter\Install\lib\site-packages\ipykernel_launcher.py:25: RuntimeWarning: invalid value encountered in multiply


IndexError: index 2 is out of bounds for axis 0 with size 2

In [12]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
P_W=np.array([[[0,0,0,1],[0,0.25,0,1],[0,0.5,0,1],[0,0.75,0,1],[0,1,0,1]],
              [[0.25,0,0,1],[0.25,0.25,0,1],[0.25,0.5,0,1],[0.25,0.75,0,1],[0.25,1,0,1]],
              [[0.5,0,0,1],[0.5,0.25,0,1],[0.5,0.5,0,1],[0.5,0.75,0,1],[0.5,1,0,1]],
              [[0.75,0,0,1],[0.75,0.25,0,1],[0.75,0.5,0,1],[0.75,0.75,0,1],[0.75,1,0,1]],
              [[1.0,0,0,1],[1.0,0.25,0,1],[1.0,0.5,0,1],[1.0,0.75,0,1],[1.0,1,0,1]]])
y=P_W.flatten()
print(y)

[0.   0.   0.   1.   0.   0.25 0.   1.   0.   0.5  0.   1.   0.   0.75
 0.   1.   0.   1.   0.   1.   0.25 0.   0.   1.   0.25 0.25 0.   1.
 0.25 0.5  0.   1.   0.25 0.75 0.   1.   0.25 1.   0.   1.   0.5  0.
 0.   1.   0.5  0.25 0.   1.   0.5  0.5  0.   1.   0.5  0.75 0.   1.
 0.5  1.   0.   1.   0.75 0.   0.   1.   0.75 0.25 0.   1.   0.75 0.5
 0.   1.   0.75 0.75 0.   1.   0.75 1.   0.   1.   1.   0.   0.   1.
 1.   0.25 0.   1.   1.   0.5  0.   1.   1.   0.75 0.   1.   1.   1.
 0.   1.  ]


In [13]:
for i in range(25):
    j1= 2*i
    j2= 2*i+1
    j3=i
    print(j3)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [14]:
C=np.array([[139000,74280,0],[74280,115400,0],[0,0,115400]])
print(C)

[[139000  74280      0]
 [ 74280 115400      0]
 [     0      0 115400]]


## Rough implementation of Stiffness Matrix generation

### Parameters

In [15]:
##*****Knot vectors must be integers****## cannot be 0.5   etc........
##*******RESTRICTION***************##
# U = np.array([0., 0., 0., 0.,0.5, 1., 1., 1., 1.])
# V = np.array([0., 0., 0., 0.,0.5, 1., 1., 1., 1.])
U = np.array([0., 0., 0., 0.,1., 2., 2., 2., 2.]) 
V = np.array([0., 0., 0., 0.,1., 2., 2., 2., 2.]) 
p=3
q=3
n=(np.size(U)-1)-p-1
m=(np.size(V)-1)-q-1
P_W_T=np.array([[[0,0,0,1],[0.25,0,0,1],[0.5,0,0,1],[0.75,0,0,1],[1,0,0,1]],
             [[0,0.25,0,1],[0.25,0.25,0,1],[0.5,0.25,0,1],[0.75,0.25,0,1],[1,0.25,0,1]],
             [[0,0.5,0,1],[0.25,0.5,0,1],[0.5,0.5,0,1],[0.75,0.5,0,1],[1,0.5,0,1]],
             [[0,0.75,0,1],[0.25,0.75,0,1],[0.5,0.75,0,1],[0.75,0.75,0,1],[1,0.75,0,1]],
             [[0,1,0,1],[0.25,1,0,1],[0.5,1,0,1],[0.75,1,0,1],[1,1,0,1]]])
P_W=np.array([[[0,0,0,1],[0,0.25,0,1],[0,0.5,0,1],[0,0.75,0,1],[0,1,0,1]],
              [[0.25,0,0,1],[0.25,0.25,0,1],[0.25,0.5,0,1],[0.25,0.75,0,1],[0.25,1,0,1]],
              [[0.5,0.,0,1],[0.5,0.25,0,1],[0.5,0.5,0,1],[0.5,0.75,0,1],[0.5,1,0,1]],
              [[0.75,0,0,1],[0.75,0.25,0,1],[0.75,0.5,0,1],[0.75,0.75,0,1],[0.75,1,0,1]],
              [[1.0,0,0,1],[1.0,0.25,0,1],[1.0,0.5,0,1],[1.0,0.75,0,1],[1.0,1,0,1]]])
P=P_W[:,:,0:3]
W=P_W[:,:,3]
d=3
print(P[0][1]*W[0][0])

[0.   0.25 0.  ]


### Stiffness matrix for 2D case with u1 and u2 dof

In [16]:
ncpx =5 # No.control points in x direction
ncpy =5 # No.control points in y direction
ncp = ncpx*ncpy
ndof = 2
# Gauss points and corresponding weights in a single matrix
# This matrix will depend on the type of problem. So have to change in parameters. 
# Or alternatively create a function
GPs_Ws = np.array([[-0.5774,-0.5774,1],[0.5774,-0.5774,1],[0.5774,0.5774,1],[-0.5774,0.5774,1]])
#GPs_Ws[:,2] gauss weights
#GPs_Ws[:,0:2] gauss points

#Have to see how to make it work for multiple elements
nel = (ncpx-p-1)*(ncpy-q-1) #Total number of elements
necp =(p+2)*(q+2) #Total number of control points in an element 
#Caution have to check on what it depends
gp=GPs_Ws[0,0:2]

In [17]:
KG = np.zeros((ndof*ncp,ndof*ncp)) #Initiating Global K matrix
RHSG = np.zeros((ndof*ncp,1)) # Initiating Global RHS matrix
for i in range(nel):
    Ke=np.zeros((ndof*necp,ndof*necp))
    B=np.zeros((3,ndof*necp)) #Dimentions depends on type of application
    elU = np.array([0,2]) #Manually defined have to generate using connectivity functions
    elV = np.array([0,2]) #Manually defined have to generate using connectivity functions
    
    for j in range(np.shape(GPs_Ws)[0]): #Computes number of gauss points from GP matrix provided
        gp = GPs_Ws[j,0:2]
        wg = GPs_Ws[j,2]
        xi_para = gp[0]
        eta_para = gp[1]
        xi = 0.5*((elU[1]-elU[0])*xi_para + (elU[1]+elU[0]))
        eta = 0.5*((elV[1]-elV[0])*eta_para + (elV[1]+elV[0]))
        dxi_dxi_para = 0.5*(elU[1]-elU[0])
        deta_deta_para = 0.5*(elV[1]-elV[0]) 
        J2 = dxi_dxi_para*deta_deta_para
        
        #--------Evaluation of NURBS basis functions derivatives---------#
        # We are finding the derivative at gauss points
        u=xi 
        #************What is point in sending xi and eta values what does that mena here????************#
        v=eta
        Aders = SurfaceDerivsAlgAuv(n,p,U,m,q,V,P,W,u,v,d)
        wders = SurfaceDerivsAlgWuv(n,p,U,m,q,V,P,W,u,v,d)
        R = RatSurfaceDerivs(Aders,wders,d)
        print(R[0][1][0])
        jacob = np.array([[R[1][0][0],R[0][1][0]],
                          [R[1][0][1],R[0][1][1]]])
        J1=np.linalg.det(jacob)

7.461393830399117e-18
-6.991143896556418e-17
0.0
0.0


## 2nd Order Element

In [18]:
##*****Knot vectors must be integers****## cannot be 0.5   etc........
##*******RESTRICTION***************##
U = np.array([0., 0., 1.,1.]) 
V = np.array([0., 0., 1.,1.]) 
p=1
q=1
n=(np.size(U)-1)-p-1
m=(np.size(V)-1)-q-1
#***********Page 116 for control points array definition ************#
P_W=np.array([[[0,0,0,1],[0,1,0,1]],
           [[1,0,0,1],[1,1,0,1]]])
P=P_W[:,:,0:3]
W=P_W[:,:,3]
d=1
ncpx =2 # No.control points in x direction
ncpy =2 # No.control points in y direction
ncp = ncpx*ncpy
ndof = 2
# Gauss points and corresponding weights in a single matrix
# This matrix will depend on the type of problem. So have to change in parameters. 
# Or alternatively create a function
GPs_Ws = np.array([[-0.5774,-0.5774,1],[0.5774,-0.5774,1],[0.5774,0.5774,1],[-0.5774,0.5774,1]])
#GPs_Ws[:,2] gauss weights
#GPs_Ws[:,0:2] gauss points

#Have to see how to make it work for multiple elements
nel = (ncpx-p-1)*(ncpy-q-1)+1 #Total number of elements
print('Number of elements are:', nel)
necp =(p+2)*(q+2) #Total number of control points in an element 
#Caution have to check on what it depends
gp=GPs_Ws[0,0:2]

Number of elements are: 1


In [19]:
KG = np.zeros((ndof*ncp,ndof*ncp)) #Initiating Global K matrix
RHSG = np.zeros((ndof*ncp,1)) # Initiating Global RHS matrix
for i in range(nel):
    Ke=np.zeros((ndof*necp,ndof*necp))
    B=np.zeros((3,ndof*necp)) #Dimentions depends on type of application
    elU = np.array([0,1]) #Manually defined have to generate using connectivity functions
    elV = np.array([0,1]) #Manually defined have to generate using connectivity functions
    
    for j in range(np.shape(GPs_Ws)[0]): #Computes number of gauss points from GP matrix provided
        gp = GPs_Ws[j,0:2]
        wg = GPs_Ws[j,2]
        xi_para = gp[0]
        eta_para = gp[1]
        xi = 0.5*((elU[1]-elU[0])*xi_para + (elU[1]+elU[0]))
        eta = 0.5*((elV[1]-elV[0])*eta_para + (elV[1]+elV[0]))
        dxi_dxi_para = 0.5*(elU[1]-elU[0])
        deta_deta_para = 0.5*(elV[1]-elV[0]) 
        J2 = dxi_dxi_para*deta_deta_para
        
        #--------Evaluation of NURBS basis functions derivatives---------#
        # We are finding the derivative at gauss points
        u=xi 
        #************What is point in sending xi and eta values what does that mena here????************#
        v=eta
        Aders = SurfaceDerivsAlgAuv(n,p,U,m,q,V,P,W,xi,eta,d)
        wders = SurfaceDerivsAlgWuv(n,p,U,m,q,V,P,W,xi,eta,d)
        R = RatSurfaceDerivs(Aders,wders,d)
        R_NURBS = SurfaceDerivsAlgNURBS(n,p,U,m,q,V,P,W,xi,eta,d)
        print(R[0][1])
        J1 = np.array([[R[1][0][0],R[0][1][0]],
                          [R[1][0][1],R[0][1][1]]])
        J1inv=np.linalg.inv(jacob)
        J1det=np.linalg.det(jacob)
        R_dxideta = np.array([R_NURBS[1][0],R_NURBS[0][1]])
        R_dxdy = np.matmul(J1inv,R_dxideta)
        
        

[0. 1. 0.]
[0. 1. 0.]
[0. 1. 0.]
[0. 1. 0.]
